repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: local
    hooks:
    -   id: tests
        name: run all tests
        entry: poetry run python -m unittest discover
        language: system
        pass_filenames: false
        verbose: true
